### ISSUE TITLE
Upgrade harfbuzz to v3

### ISSUE THREAD

**Issue by yisibl** [harfbuzz/harfbuzz_rs#33]
Do we plan to upgrade to harfbuzz v3?

Starting from 3.0, The hb-subset API and the harfbuzz-subset library's ABI are now declared stable.

**Comment by behdad** [comment]
https://github.com/harfbuzz/harfbuzz_rs/pull/34

**Comment by yisibl** [comment]
Awesome, harfbuzz_rs is now taken over by the harfbuzz team?

**Comment by behdad** [comment]
> Awesome, harfbuzz_rs is now taken over by the harfbuzz team?

We like to help where we can. :)
