### ISSUE TITLE
crates.io access

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz_rs#45]
@manuel-rhdt Hi. Can you please pass on the crates.io project to @khaledhosny if you won't be updating it? Thanks.

**Comment by asibahi** [comment]
I think it is possible that, if Manuel does not reply, it is possible to contact crates.io team directly.

**Comment by behdad** [comment]
Maniel seems inactive.  I emailed crates.io people.

**Comment by manuel-rhdt** [comment]
Hi, I‘m sorry for not responding earlier. I will pass on the crates.io access to @khaledhosny .

**Comment by khaledhosny** [comment]
Thanks, I accepted the invitation.
